### PR TITLE
Add SQuAD dataset to chazutsu.datasets module

### PR DESCRIPTION
**Pull request by yasufumy**
- Add `Squad` class to `chazutsu.datasets` module
- Add `TestSquad` class as a test case for the class
- Check all other test case passed

### CODE REVIEW

**Comment by icoxfog417** [comment]
Please change single quote to double quote for code consistency.

**Comment by yasufumy** [comment]
updated squad.py and test_squad.py

**Comment by icoxfog417** [comment]
Thanks! Finally, please change class name `Squad` to `SQuAD` (`class Squad(Dataset):` => `class SQuAD(Dataset):`).

**Comment by yasufumy** [comment]
We need to discuss how to handle unanswerable question in SQuAD v2.0.

**Comment by yasufumy** [comment]
- Add support for SQuAD v2.0
- Add test case for SQuAD v2.0
- Update `README.md` and `chazutsu/README.md`

**Pull request merged**
